typography_spectrum: 0.3506981
color:
  saturation: 1
  brandStrength: 0.9747583
  lightness: 0.5354457
  brandColors:
    - '#E4C6AE'
    - '#080300'
    - '#FFFCF9'
    - '#7C5D49'
    - '#A07C62'
  rhythmicContrast: 1
github: true
layout_spectrum: 0.8469387
author:
  name: Claudio lara
  email: nlpclaudiolara@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7239b411-4b47-4c9f-85d7-14b957528632.png
name: GenialidadebyClaudiolara
url: 'http://www.claudiolara.com.br'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Genialidade
content: []
description: Aprenda a ser genial com Claudio Lara
purpose: []
