layout_spectrum: 0.1748624779360535
typography_spectrum: 0.355168492301819
color:
  saturation: 0.9974082603447582
  brandStrength: 0.9705464657223645
  lightness: 0.5308801668905423
  brandColors:
    - '#E4C6AE'
    - '#080300'
    - '#FFFCF9'
    - '#7C5D49'
    - '#A07C62'
  rhythmicContrast: 0.9977847482378382
github: true
author:
  name: Claudio lara
  email: nlpclaudiolara@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7239b411-4b47-4c9f-85d7-14b957528632.png
name: GenialidadebyClaudiolara
url: 'http://www.claudiolara.com.br'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Genialidade
content: []
description: Aprenda a ser genial com Claudio Lara
purpose:
  - type: external
    url: 'https://www.facebook.com'
    label: Facebook Page
  - type: contact
    url: 'mailto:nlpclaudiolara@gmail.com'
    label: Contato
