layout_spectrum: 1
color:
  saturation: 0.5966703
  lightness: 0.5343716
  brandStrength: 0.3813578
  brandColors:
    - '#150F0C'
    - '#FFFFFB'
    - '#783016'
    - '#F0C9A2'
    - '#938688'
  rhythmicContrast: 0.537594
typography_spectrum: 0.1068743
name: 'ClaudioLaraOficial '
